# Generated by Django 4.2.19 on 2025-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct_answers',
            field=models.CharField(default='', max_length=200),
        ),
    ]
